// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-2oW76_hG5oS2bAbwMkJCtJ7Bz7YdkA',
    appId: '1:262535965607:web:ddc1a535f50e2f172e2482',
    messagingSenderId: '262535965607',
    projectId: 'lolfirenotes',
    authDomain: 'lolfirenotes.firebaseapp.com',
    storageBucket: 'lolfirenotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEorqdcBKZa6Tm6HZmn5bCIssUY-jRhUM',
    appId: '1:262535965607:android:14f5f51c8314c6e02e2482',
    messagingSenderId: '262535965607',
    projectId: 'lolfirenotes',
    storageBucket: 'lolfirenotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzYocLcGAWfTksermNZUYS6Gwtv_6c38',
    appId: '1:262535965607:ios:14fd7b9e90cb77f52e2482',
    messagingSenderId: '262535965607',
    projectId: 'lolfirenotes',
    storageBucket: 'lolfirenotes.appspot.com',
    iosClientId: '262535965607-30lhrho5630p4iq1cju5n7krc6ldvcvd.apps.googleusercontent.com',
    iosBundleId: 'com.lolsite.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzzYocLcGAWfTksermNZUYS6Gwtv_6c38',
    appId: '1:262535965607:ios:aa9ce21bd46208eb2e2482',
    messagingSenderId: '262535965607',
    projectId: 'lolfirenotes',
    storageBucket: 'lolfirenotes.appspot.com',
    iosClientId: '262535965607-hmvuk9fv4bdjrss8gbb6s63kvulcs78b.apps.googleusercontent.com',
    iosBundleId: 'com.lolsite.mynotes.RunnerTests',
  );
}
